packages:
    - adlc
    - apps/**
    - modules/**
    - packages/**

onlyBuiltDependencies:
    - "@parcel/watcher"
    - agent-browser
    - core-js
    - edgedriver
    - esbuild
    - geckodriver
    - msw
    - netlify-cli
    - playwright
    - protobufjs
    - sharp
    - unix-dgram
